---
- name: Configuring Network
  hosts: 
    - astra11
  vars:
    config_network_bonds: true
    config_network_bridges: true
    config_network_interfaces: true
    config_network_vlans: true
    enable_configured_interfaces_after_defining: true
#####################################################
    network_bonds:
      - name: bond0
        address: 10.15.140.2
        netmask: 255.255.255.192
        gateway: 10.15.140.62
        configure: true
        enable: false
        comment: Bond Group 0
        method: static
        parameters:
          - param: bond_mode
            val: 4
          - param: bond_miimon
            val: 100
          - param: bond_xmit_hash_policy
            val: layer3+4
          - param: bond_lasp_rate
            val: fast
        slaves:
          - eno1
          - eno2
###
      - name: bond1
        configure: true
        enable: false
        comment: Bond Group 1
        method: manual
        parameters:
          - param: bond_mode
            val: 4
          - param: bond_miimon
            val: 100
          - param: bond_xmit_hash_policy
            val: layer3+4
          - param: bond_lasp_rate
            val: fast
        slaves:
          - enp95s0f0
          - eno95s0f1
#############################################################
    network_vlans:
      - name: bond0.2260
        configure: true
        enable: false
        comment: VLAN 2260
        method: manual
#        address:
#        netmask:
#        netmask_cidr:
#        gateway:
        vlan_device: bond0
###
      - name: bond0.2210
        configure: true
        enable: false
        comment: VLAN 2210
        method: manual
#        address:
#        netmask:
#        netmask_cidr:
#        gateway:
        vlan_device: bond0
###
      - name: bond1.1200
        configure: true
        enable: false
        comment: VLAN 1200
        method: manual
#        address:
#        netmask:
#        netmask_cidr:
#        gateway:
        vlan_device: bond1
################################################################
    network_bridges:
      - name: br_srv
        configure: true
        enable: false
        comment: Bridge br_srv
        method: static
        address: 10.15.140.194
        netmask: 255.255.255.192
        #        netmask_cidr: 26
#       gateway: 10.15.140.254
        parameters:
          - param: bridge_stp
            val: off
          - param: bridge_fd
            val: 0
  #           # - param: up route add default gw
  #           #   val: 10.0.106.1
        ports:
          - bond0.2260
###
      - name: br_mgt
        configure: true
        enable: false
        comment: Bridge br_mgt
        method: static
        address: 10.15.140.66
        netmask: 255.255.255.192
        #        netmask_cidr: 26
#        gateway: 10.15.140.126
        parameters:
          - param: bridge_stp
            val: off
          - param: bridge_fd
            val: 0
            # - param: up route add default gw
            #   val: 10.0.106.1
        ports:
          - bond0.2210
###
      - name: br_stg
        configure: true
        enable: false
        comment: Bridge br_stg
        method: static
        address: 10.15.141.2
        netmask: 255.255.255.192
#        netmask_cidr: 26
#        gateway: 10.15.140.126
        parameters:
          - param: bridge_stp
            val: off
          - param: bridge_fd
            val: 0
            # - param: up route add default gw
            #   val: 10.0.106.1
        ports:
          - bond1.1200
  
            
  #     - name: u-portal
  #       configure: true
  #       enable: false
  #       comment: Bridge u-portal
  #       method: static
  #       address: 10.15.140.131
  # #        netmask: 255.255.255.0
  #       netmask_cidr: 26
  #       gateway: 10.15.140.190
  #       parameters:
  #         - param: bridge_stp
  #           val: off
  #         - param: bridge_fd
  #           val: 0
  #           # - param: up route add default gw
  #           #   val: 10.0.106.1
  #       ports:
  #         - bond0.2220
  #
  #
##################################################
    network_interfaces:
      - name: eno1
        configure: true
#        comment: bond0 member
        method: manual
#        parameters:
#          - param: bond_master
#            val: bond0
      - name: eno2
        configure: true
#        comment: bond0 member
        method: manual
#        parameters:
#          - param: bond_master
#            val: bond0
      - name: enp95s0f0
        configure: true
#        comment: bond1 member
        method: manual
#        parameters:
#          - param: bond_master
#            val: bond1
      - name: enp95s0f1
        configure: true
#        comment: bond1 member
        method: manual
#        parameters:
#          - param: bond_master
#            val: bond1

##################################################
    pri_domain_name: deploy.openstack.local
  roles:
     - ansible-config-interfaces-master
#  tasks:
#     - debian.yml
