---
- name: Configuring Network
  hosts: 
    - astra11
  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Generate net_vars config
      read_csv:
        path: "{{ ipam_file }}"
        dialect: "excel-tab"
        #        fieldnames: var_host_name,var_serial
        delimiter: ','
      register: hosts
      delegate_to: localhost

    - name: create file
      template:
        src: "{{ net_vars_template }}"
        dest: host_vars/{{ item.var_host_name }}
      loop: "{{ hosts.list }}"
      delegate_to: localhost

  roles:
     - ansible-config-interfaces-master

